### ISSUE TITLE
No login page is presented on very first start of the app

### ISSUE THREAD

**Issue by nanosonde** [psaraci/risipapp#3]
This caused due the code in MainWindow.qml which handles the "Let's start"-button.
It has to be rearranged a bit so that there is a sipAccount object and not NULL:

```    Connections {
        target: welcomeScreenLoader.item
        onEnterClicked: {
            if(!firstRun) {
                if(sipAccount.status === RisipAccount.SignedIn) {
                    loginPageLoader.active = false;
                    mainPageLoader.item.visible = true;
                } else {
                    mainPageLoader.item.visible = false; //main page is not visible because account is not signed int
                }
                welcomeScreenLoader.active = false; //disabling welcome screen on enter clicked
            } else {
               loginPageLoader.active = true;
               mainPageLoader.item.visible = false; //main page is not visible because account is not signed int
               welcomeScreenLoader.active = false; //disabling welcome screen on enter clicked
            }
        }
    }
```
sipAccount.status cannot be read, because there was never an account setup after first installation of the app.

**Comment by kastravec** [comment]
That is correct, on first run there is no sip account configured. Note that once an account is added, then it will be saved on disk so next time loaded it will be there.

Have you managed to have the app running now?

**Comment by nanosonde** [comment]
Yes, it is running now and I was able to place and receive calls. Audio is also working.
However, I replaced the existing PJSIP version with the latest 2.6.0.

Concerning the account creation above:
Without changing the code in MainView.qml you will never reach the page where you can create an account.
It seems that QML does NOT execute the code any further after it detected that the object "sipAccount" is NULL, so that accessing the property sipAccount.status is not possible.

```
qrc:/ui/base/MainWindow.qml:89: TypeError: Cannot read property 'status' of null
```

That's why I have used the check for firstRun BEFORE trying to access sipAccount.

**Comment by kbu9999** [comment]
Try this

if(sipAccount && sipAccount.status === RisipAccount.SignedIn) {
                loginPageLoader.active = false;
                mainPageLoader.item.visible = true;
} else { ......

**Comment by kbu9999** [comment]
try this
```
if(sipAccount && sipAccount.status === RisipAccount.SignedIn) {
                loginPageLoader.active = false;
                mainPageLoader.item.visible = true;
} else { ...
```

**Comment by kastravec** [comment]
@chrwick @kbu9999 

interested in patching this up and upstreaming it?

**Comment by kbu9999** [comment]
I do not speak english very well.
but i will try to upload it an others.
awesome project.

**Comment by kastravec** [comment]
@kbu9999 no need to speak english..just code is ok 👍 lets make this project more awesome
