### ISSUE TITLE
Cannot read  voipsdk.pri: No such file or directory

### ISSUE THREAD

**Issue by hackertron** [psaraci/risipapp#4]
hey i just git cloned the project and opened it in Qt creator . 

i am getting following error : 
Cannot read /home/nightmare/Public/risipapp/risipapp/risip-voipsdk/risip-voipsdk.pri: No such file or directory

**Comment by kastravec** [comment]
you need the rispisdk too

please check and read carefully the instructions here:
https://github.com/psaraci/risip
