### ISSUE TITLE
error: C1083: Cannot open include file: 'pjsua2.hpp': No such file or directory

### ISSUE THREAD

**Issue by hackertron** [psaraci/risipapp#5]
hello , i downloaded the risiapp from github and then downloaded risip-voipsdk and placed it into the risiapp folder .

now when i tried to build it i got this error  
C:\Users\Documents\risipapp-master\risipapp-master\risip-voipsdk\src\risipsdk\headers\risipaccountconfiguration.h:24: error: C1083: Cannot open include file: 'pjsua2.hpp': No such file or directory

System i am using 

windows 10 , Qt 5.9 .

**Comment by kastravec** [comment]
Hi, that is because i do not have a ready build of pjsip for windows unfortunately. 

You need to build this yourself i am afraid. 

Currently it will work out of the box on mac, linux
