### ISSUE TITLE
unable to build on linux system

### ISSUE THREAD

**Issue by hackertron** [psaraci/risipapp#6]
Hey , i followed the instructions and git cloned risip sdk and risipapp . when i click on build in qt creator i get these errors 

![error](https://user-images.githubusercontent.com/7667514/32403847-40cf351e-c16a-11e7-9f92-e9eea72159bf.png)

**Comment by kastravec** [comment]
So lets make a clean folder and start from the beginning.

1.Clone rispiapp 
2.Inside the risipapp folder you need to clone the risip-sdk --> once you have cloned this then you need to rename the folder from risip to risip-voipsdk
3. Open Qt Creator and open the risipapp project and you will see Risipapp and inside the risip-voipsdk (just like shown in your screenshot)
4. Just press build/run and everything should be built properly

I just tested it again and everything just works --> so something could be wrong with you setup.

Troubleshooting
5. in Qt Creator, in the project-explorer, please click to expand the risip-voipsdk project-folder to see what is included - send a screenshot
6. In Qt Creator to see properly the compiler issues, you need to click on the "Compiler issue" footer tab to get the whole compiler output, copy-paste here the complete error parts - start from beginning.

**Comment by hackertron** [comment]
It failed again .

Directory structure : 

![struct](https://user-images.githubusercontent.com/7667514/32413104-361fdd46-c230-11e7-8357-9d55c0d32e65.png)


Compile tab output : 

![error](https://user-images.githubusercontent.com/7667514/32413108-593b6dae-c230-11e7-888f-432d1bae7e09.png)


Complete compile output : 
https://pastebin.com/50VpCxaD


Also my gcc is this  : gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
Could this be a issue ? ( because on readme it was GCC4.x something )

**Comment by kastravec** [comment]
Strange compiler error, the compiler version should be fine.
Did you change the files by any chance? the .pro file or any of the .pri files? are you using ubuntu in vmware ?

**Comment by kastravec** [comment]
The error starts right at the beginning of the compilation, see below in the line " _/usr/include/c++/5/bits/locale_facets.h:2632:44: error: macro "isblank" passed 2 arguments, but takes just 1
     isblank(_CharT __c, const locale& __loc)_ "

the error is strange, but something to do with the setup of your development environment in my opinion..

see below where the error starts, it does not seem to fail in any of the risip source code, but somewhere else..

g++ -c -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DRISIP_SDK -DPJ_IS_LITTLE_ENDIAN=1 -DPJ_IS_BIG_ENDIAN=0 -DPJ_AUTOCONF -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../risiapp -I. -I../risiapp/risip-voipsdk/platforms/linux/pjsip/include -I../risiapp/risip-voipsdk/src/risipsdk/headers -I../risiapp/risip-voipsdk/src/risipsdk/headers/models -I../risiapp/risip-voipsdk/src/risipsdk/headers/apploader -I/home/nightmare/Public/risiapp/risip-voipsdk/src/risipsdk/headers/location -I/home/nightmare/Public/risiapp/risip-voipsdk/src/risipsdk/headers/sipprovision -I../risiapp/risip-voipsdk/src/risipsdk/headers/utils -I../../Qt5.9.0/5.9/gcc_64/include -I../../Qt5.9.0/5.9/gcc_64/include/QtQuickControls2 -I../../Qt5.9.0/5.9/gcc_64/include/QtQuick -I../../Qt5.9.0/5.9/gcc_64/include/QtGui -I../../Qt5.9.0/5.9/gcc_64/include/QtQml -I../../Qt5.9.0/5.9/gcc_64/include/QtNetwork -I../../Qt5.9.0/5.9/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++ -o risipaccount.o ../risiapp/risip-voipsdk/src/risipsdk/risipaccount.cpp
In file included from /usr/include/c++/5/bits/basic_ios.h:37:0,
                 from /usr/include/c++/5/ios:44,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iterator:64,
                 from ../../Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h:53,
                 from ../../Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h:49,
                 from ../../Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h:47,
                 from ../../Qt5.9.0/5.9/gcc_64/include/QtCore/QObject:1,
                 from ../risiapp/risip-voipsdk/src/risipsdk/headers/risipaccountconfiguration.h:27,
                 from ../risiapp/risip-voipsdk/src/risipsdk/headers/risipaccount.h:25,
                 from ../risiapp/risip-voipsdk/src/risipsdk/risipaccount.cpp:21:
/usr/include/c++/5/bits/locale_facets.h:2632:44: error: macro "isblank" passed 2 arguments, but takes just 1
     isblank(_CharT __c, const locale& __loc)
                                            ^
/usr/include/c++/5/bits/locale_facets.h:2632:5: error: ‘std::isblank’ declared as an ‘inline’ variable
     isblank(_CharT __c, const locale& __loc)
     ^
/usr/include/c++/5/bits/locale_facets.h:2632:5: error: ‘template<class _CharT> bool std::isblank’ conflicts with a previous declaration
In file included from /usr/include/c++/5/string:43:0,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from ../../Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h:109,
                 from ../risiapp/risip-voipsdk/src/risipsdk/headers/risipsdkglobal.h:23,
                 from ../risiapp/risip-voipsdk/src/risipsdk/headers/risipaccount.h:24,
                 from ../risiapp/risip-voipsdk/src/risipsdk/risipaccount.cpp:21:
/usr/include/c++/5/bits/localefwd.h:113:5: note: previous declaration ‘namespace std { }::isblank’
     isblank(_CharT, const locale&);
     ^

**Comment by hackertron** [comment]
What do you suggest i should do ? What's your development environment , can you please share it .

Thanks !!

**Comment by hackertron** [comment]
Nope didn't touched .pro file or .pri file . I am not using VM .

**Comment by kastravec** [comment]
this is certainly an issue with your compiler setup and the setup of c++ libs, not related to risip at all.

Just googling the error message, i found this and the same problem:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778115

having the same error:

/usr/include/c++/5/bits/locale_facets.h:2632:44: error: macro "isblank" passed 2 arguments, but takes just 1 isblank(_CharT __c, const locale& _loc) "

so please read it and search for more on how to fix it for your ubuntu.

let me know

**Comment by hackertron** [comment]
Hey i am trying to fix this issue on my system , till then can you please share following ?

1. share your development environment / system  : this can help me resolve my issue faster . 
2. Can you provide the APK of risipapp  : want to test it out ( really need it ).
3.  linux build for risipapp ( if possible )

**Comment by KISSMonX** [comment]
same error。
strange error。
**Have you solved this problem?**

**Comment by shabunin** [comment]
I was able to run with gcc/g++ 9.2.0
Take a look:
https://trac.pjsip.org/repos/ticket/2019
https://trac.pjsip.org/repos/changeset/5599
