### ISSUE TITLE
Rendeing issues on Android 8.1.0

### ISSUE THREAD

**Issue by angiglesias** [psaraci/risipapp#7]
Compiled and loaded the app on a Samsung J7 running Android 8.1.0 and app screeens are rendered out of phone screen limits

![Screenshot_20190618-105537](https://user-images.githubusercontent.com/26471934/59667968-f2334600-91b7-11e9-827f-e026aec53f53.jpg)
![Screenshot_20190618-105542](https://user-images.githubusercontent.com/26471934/59667969-f2334600-91b7-11e9-87da-d3dd9a111773.jpg)

**Comment by kastravec** [comment]
Yes, unfortunately I don't have the time to resolve such issues. This is just a reference implementation and should be fairly easy to resolve such problems.
